# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
#markdown: kramdown
markdown: GFM
highlighter: rouge
permalink: pretty

#markdown: redcarpet
#redcarpet:
#  extensions:
#    - no_intra_emphasis
#    - fenced_code_blocks
#    - autolink
#    - tables
#    - strikethrough
#    - superscript
#    - with_to_data
    
collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: XX Simple 6D Space Know (1)

